const errorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TASK_NOT_FOUND: "TASK_NOT_FOUND",
    INVALID_FIELDS: "INVALID_FIELDS",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    VALIDATION_ERROR:"VALIDATION_ERROR"
  };
  
  module.exports = errorCodes;
  